name: dart_functions
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/kenresoft/dart_functions

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
